# -*- coding: utf-8 -*-
"""Premier League 2021-22 Data Analysis (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bJ7XKTqxogRV-q7Lt5pOT0RH_cHts2KN

In this project, we will be performing exploratory data analysis on the dataset for the 2021-22 English Premier League season.
"""

#import
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import seaborn as sns
import math

#import dataset
epl = pd.read_csv("EPL22.csv",encoding='latin1')
epl.head()

epl.info()

display(epl.describe())

epl.isna().sum()

epl

dependent_columns = ['Min', '90s', 'Gls', 'Ast', 'G-PK','PK','PKatt','CrdY','CrdR','Gls.1','Ast.1','G+A','G-PK.1','G+A-PK'
,'xG' 
,'npxG'
,'xA' 
,'npxG+xA' 
,'xG.1'
,'xA.1' 
,'xG+xA'
,'npxG.1'
,'npxG+xA.1']

epl.loc[epl['MP'] == 0, dependent_columns] = epl.loc[epl['MP'] == 0, dependent_columns].fillna(0)

epl

epl.isna().sum()

#drop missing values
epl=epl.dropna()
epl.isna().sum()

#Total Goals
Total_Goals= math.trunc(epl['Gls'].sum())
print('Total Goals Scored in 2021/22: ',Total_Goals)

#Total Assists
Total_Assists= math.trunc(epl['Ast'].sum())
print('Total Assists in 2021/22: ',Total_Assists)

#Total Penalties Scored
Total_Pen= math.trunc(epl['PK'].sum())
print('Total penalties scored in 2021/22: ',Total_Pen)

#Total Penalties Attempted
Total_Penatt= math.trunc(epl['PKatt'].sum())
print('Total penalties attempted in 2021/22: ',Total_Penatt)

#Total Yellow cards
Total_Y= math.trunc(epl['CrdY'].sum())
print('Total Yellow Cards in 2021/22: ',Total_Y)

#Total Red cards
Total_R= math.trunc(epl['CrdR'].sum())
print('Total Red Cards in 2021/22: ',Total_R)

#Total Bookings
Total_Bookings= Total_Y+Total_R
print('Total Bookings in 2021/22: ',Total_Bookings)

#Pie Chart for Penalties
pk_notscored= Total_Penatt-Total_Pen
plt.figure(figsize=(13,6))
pendata=(pk_notscored, Total_Pen)
labels= ['Penalties Missed','Penalties Scored']
color= sns.color_palette('Set1')
plt.pie(pendata, colors=color, labels=labels, autopct='%.0f%%')
plt.show()

"""Out of a 103 spotkicks, 82% were converted and 18% were missed!"""

#Goals with/without assists
assists=epl['Ast'].sum()
goals=epl['Gls'].sum()
plt.figure(figsize=(13,6))
data=[goals - assists, assists]
labels= ['Goals without assists','Goals with assists']
color= sns.color_palette('Set2')
plt.pie(data, colors=color, labels=labels, autopct='%.0f%%')
plt.show()

"""In this season, 1037 goals were scored out of which 72% were assisted while 28% were solo goals."""

#Unique Positions
epl["Pos"].unique()

#Total FW players

epl[epl['Pos']=='FW']

np.size((epl['Nation'].unique()))

"""Players from 66 different nations!"""

epl['Team'].unique()

# Assign default color
default_color = 'gray'

# Assign color dictionary
colors= {'Arsenal':'firebrick', 'Aston Villa':'maroon', 'Brentford':'pink', 'Brighton & Hove Albion':'cornflowerblue',
       'Burnley':'purple', 'Chelsea':'midnightblue', 'Crystal Palace':'blue', 'Everton':'navy', 'Leeds United':'ivory',
       'Leicester City':'mediumblue', 'Liverpool':'crimson', 'Manchester City':'skyblue',
       'Manchester United':'red', 'Newcastle United':'black', 'Norwich City':'yellow',
       'Southampton':'darksalmon', 'Tottenham Hotspur':'white', 'Watford':'gold', 'West Ham United':'brown',
       'Wolverhampton Wanderers':'orange'}

# Map colors to teams
epl.loc[:,'color'] = epl['Team'].map(colors).fillna(default_color)

#Most players from which nation

nationality = epl.groupby('Nation').size().sort_values(ascending=False)
nationality.head(10).plot(title= 'No. of players by Nation', kind= 'bar', figsize= (12,6), color=sns.color_palette('magma'))

"""Highest number of players were English- that is almost 4 times more than French/Spanish and other top nations. No surprise there since its the EPL!"""

epl['Team'].value_counts().nlargest(5).plot(title= 'Clubs with the largest squads', kind= 'bar', figsize= (12,6), color = [colors[x] for x in epl['Team'].value_counts().nlargest(5).index],edgecolor = 'black')

"""Arsenal and Aston Villa have the highest number of players in their squads."""

epl['Team'].value_counts().plot(title= 'No. of Squad Players in all Premier League Clubs', kind= 'bar', figsize= (12,6), color = [colors[x] for x in epl['Team'].value_counts().index],edgecolor = 'black')

epl['Team'].value_counts().nsmallest(5).plot(title= 'Clubs with the smallest squad', kind= 'bar', figsize= (12,6), color = [colors[x] for x in epl['Team'].value_counts().nlargest(5).index],edgecolor = 'black')

"""The highest number of players in a squad is 42 (Arsenal and Aston Villa) while all the other teams except Southampton have atleast 30 players in their squads. """

#Player Age Groupings

under_20= epl[epl['Age']<20.0]
age20_25= epl[(epl['Age']>=20.0) & (epl['Age']<=25.0)]
age26_30= epl[(epl['Age']>25.0) & (epl['Age']<=30.0)]
above_30= epl[epl['Age']>30.0]

x= np.array([under_20['Player'].count(), age20_25['Player'].count(), age26_30['Player'].count(), above_30['Player'].count()])
agelabels= ['<20','20-25','26-30','<30']
plt.title('Player Age Groups', fontsize=16)
plt.pie(x, labels=agelabels, autopct='%.1f%%')
plt.show

"""Young players (25 and under) make up 58.6% of the player base. This % is expected to keep growing in the coming years as academies are bringing in more talent and clubs are signing high potential youngsters."""

# Under 20 players in each club
under_20_pl= epl[epl['Age']<20]
under_20_pl['Team'].value_counts().plot(kind='bar',figsize= (12,6), color = sns.color_palette('cubehelix'),edgecolor = 'black')

"""Arsenal has the highest number of youngsters under the age of 20. Surprisingly, Chelsea has the lowest number of youngsters despite having one of the best academies in the EPL with notable talents such as Reece James and Mason Mount emerging from their academy in recent years."""

# Under 20 Players in Arsenal

under_20_pl[epl['Team']=='Arsenal']

# Average Age
plt.figure(figsize=(12,6))
sns.boxplot(x='Team',y='Age',data=epl)
plt.xticks(rotation=90)

player_num= epl.groupby('Team').size()
data= (epl.groupby('Team')['Age'].sum()) / player_num
data.sort_values(ascending=False)

"""Burnley has the highest average age (27.03) out of all the teams in the EPL. Arsenal have the lowest (22.48) which makes sense since they have been heavily investing in their youth players and have the highest number of under 20 players in their squad."""

# Assists by each team

team_asst= pd.DataFrame(epl.groupby('Team', as_index= False)['Ast'].sum())
sns.set_theme(style='whitegrid', color_codes= True)
ax = sns.barplot(x='Team', y='Ast', data=team_asst.sort_values(by='Ast'), palette='Set2')
ax.set_xlabel('Team', fontsize=20)
ax.set_ylabel('Assists', fontsize=20)
plt.xticks(rotation=90)
plt.rcParams['figure.figsize']=(20,8)
plt.title('Total Assists by each Team', fontsize=20)

"""Liverpool held the record for the highest number of assists (71) in the 2021/22 season."""

liv_asst=epl[epl['Team']=='Liverpool'].groupby('Player').sum()
liv_asst['Ast'].sum()

#Top 10 Assist Providers
top_10_ast= epl[['Player','Team','Ast','MP']].nlargest(n=10, columns='Ast')
top_10_ast

"""Mo Salah was the leader in assists during the 2021/22 season, while Trent Alexander-Arnold and Andrew Robertson also featured in the top 5. No wonder Liverpool had the highest number of assists!"""

# Goals by each team

team_gls= pd.DataFrame(epl.groupby('Team', as_index= False)['Gls'].sum())
sns.set_theme(style='whitegrid', color_codes= True)
ax = sns.barplot(x='Team', y='Gls', data=team_gls.sort_values(by='Gls'), palette='rocket')
ax.set_xlabel('Team', fontsize=20)
ax.set_ylabel('Goals', fontsize=20)
plt.xticks(rotation=90)
plt.rcParams['figure.figsize']=(20,8)
plt.title('Total Goals by each Team', fontsize=20)

team_gls= pd.DataFrame(epl.groupby('Team', as_index= False)['Gls'].sum())
team_gls.nlargest(n=3, columns= 'Gls')

"""Manchester City had the highest number of goals in the season, despite not having a proper striker! """

#Top Scorers
top_10_gls= epl[['Player','Team','Gls','MP']].nlargest(n=10, columns='Gls')
top_10_gls

"""Mo Salah and Son Heung-min were the joint top scorers with 23 goals each and shared the Golden Boot award. Surprisingly, none of the Manchester City players featured in the top 5 even though City had the highest number of goals for the season. """

#Goals Per Match

epl['GoalsPerMatch']= epl['Gls'] / epl['MP']

top_10_gpm= epl[['Player','Team','GoalsPerMatch','MP']].nlargest(n=10, columns='GoalsPerMatch')
top_10_gpm

"""The joint top-scorers, Mo Salah and Son, played the same number of matches (35) and scored the same number of goals (23)."""

#Highest non penalty xG+A
top_10_npxga= epl[['Player','Team','npxG+xA','MP']].nlargest(n=10, columns='npxG+xA')
top_10_npxga

"""Mo Salah had the highest non penalty expected goals and assists, which shows how threatening he was throughout the season. Harry Kane and Son were slightly behind. Son won the Golden Boot along with Salah, however Kane's underlying stats tell us a different story. While Kane was in optimal scoring and assisting positions and remained a constant threat, his output was not as clinical which is why there's a disparity in his numbers."""